#!/bin/sh

opkg update
opkg install php5-fastcgi php5-mod-gd

# remove unnecessary files after install
rm /tmp/opkg-lists/*

# In OpenWrt, the php-cgi binaries are in /usr/bin, which
# I don't want to expose as a Directory, so copy them
mkdir /usr/share/php5-cgi
mv /usr/bin/php-cgi /usr/bin/php-fcgi /usr/share/php5-cgi/

# # configure apache for php mime time and php cgi
# sed -i -e 's/ScriptAlias \/cgi-bin\/\(.*\)/ScriptAlias \/cgi-bin\/\1\n    ScriptAlias \/php\/ "\/usr\/bin\/"/' /etc/apache/httpd.conf
# sed -i -e 's/AddType application\/x-gzip .gz .tgz/AddType application\/x-gzip .gz .tgz\n    AddType application\/x-httpd-php .php/' /etc/apache/httpd.conf
# printf '\n\nAction application/x-httpd-php "/php/php-cgi"\n\n' >> /etc/apache/httpd.conf

# # FIXME: don't use /usr/bin -> move php-cgi somewhere else and use that directory
# sed -i -e 's/<Directory "\/usr\/share\/cgi-bin">/<Directory "\/usr\/bin">\n    AllowOverride None\n    Options none\n    Order allow,deny\n    Allow from all\n<\/Directory>\n<Directory "\/usr\/share\/cgi-bin">/' /etc/apache/httpd.conf

# sed -i -e 's/DirectoryIndex index.html/DirectoryIndex index.php index.html/' /etc/apache/httpd.conf

# Configure php
sed -i -e 's/doc_root =.*/doc_root = ""/' /etc/php.ini
sed -i -e 's/;extension=gd.so/extension=gd.so/' /etc/php.ini

# create a php file to be able to test the functionality
mkdir /usr/share/htdocs/test
echo "<?php phpinfo(); ?>" > /usr/share/htdocs/test/index.php
