#!/bin/sh

opkg update
opkg install --force-checksum php5-fastcgi php5-mod-gd

# remove unnecessary files after install
rm /tmp/opkg-lists/*

# In OpenWrt, the php-cgi binaries are in /usr/bin, which
# I don't want to expose as a Directory, so copy them
# but beware that the php5-fcgi daemon still uses the one
# in /usr/bin
#
# NOTE: this dir must be in sync with the content in etc/apache/conf/php5-cgi.conf
mkdir /usr/share/php5-cgi
cp /usr/bin/php-cgi /usr/bin/php-fcgi /usr/share/php5-cgi/

# Create a dir for the php session files
# NOTE: this dir must be in sync with etc/php5/php5-additional.ini
mkdir /tmp/phpsess
chown nobody /tmp/phpsess
